### ISSUE TITLE
GitHub和GitBook的关联？

### ISSUE THREAD

**Issue by cici1989** [sunmmy/6godspy#2]
# ——副标题，在GitBook怎么才算公开发表图书？

是完成昨天组长的紧急任务时遇到的问题，当我输入这个链接 http://cici19891.gitbooks.io/mypy/content/
 会显示 **\* 'No builds exist for this book'  **\* 的报错，当我键入书的链接https://www.gitbook.com/book/cici19891/mypy
 在点击 read 后会显示 **\* 'This book has not been published yet' **\* 这样的报错。
两个链接我没有用Markdown的语法，就是想给大家看看链接是什么。
这是什么问题？

**Comment by nora614** [comment]
我好像错过了紧急内容。。。是不是在我加进来之前发的？可以给我转发一下吗？谢谢

**Comment by nora614** [comment]
我看到了，昨天发到了群里面的那个，，，打扰大家了

**Comment by cici1989** [comment]
# 是否为双推问题的调试

## 这是我Vim完成后的样子：

![](http://img0.ph.126.net/9M5wZ5RoypQuCBFcsCJY7A==/6608219914075294596.jpg)

## 这是push之后：

![](http://img1.ph.126.net/mfGYGe7IbwEtgrJQewMj-g==/6630736812698959405.jpg) 

# 请问队友们，有什么问题吗？

**Comment by nora614** [comment]
昨天我进行双推的是我自己的私人库，今天要完成紧急任务的时候发现自己的pythoncamp0这个库在gitbook上没有显示封面图片，于是按照git add,git commit,git push进行了一下，最后一步报错，报错信息如下：

请大家看看这是怎么回事

**Comment by cici1989** [comment]
你的信息没显示呢

**Comment by nora614** [comment]
请问是什么信息没显示呢？

刚才试了一下强推，最后一行显示的是：fatal: unable to access 'https://github.com/nora614/pythoncamp0.git/': Failed to connect to github.com port 443: Connection refused

**Comment by ZoomQuiet** [comment]
只要不影响最终目标的,都可以先搁置的,
别折腾主线任务之外的技术细节

**Comment by cici1989** [comment]
# 出现“TypeError: Cannot read property 'text' of undefined”

> 将大妈的回复邮件又尝试之后依然不能发布图书，同时我收到了gitbook的build book失败的邮件，如下：

![](http://img0.ph.126.net/hR5T1dI92SK_GfwXDmwEDg==/6630580682047859550.jpg) 

> 确定不是双推的问题，在邮件给出的链接中找到关键词 install、plugins ，所以进行尝试了安装nodej使用命令来解决 GitBook 的 build 问题。
> 
> 但是出现了如题所示 Error，请问是什么错误？是我的摸索的具体过程：

### 下载并安装 [Nodejs](https://nodejs.org)

```
 $ note -v
 显示"v0.12.0"表示已安装。 
```

### GitBook命令

```
 $ gitbook -V     
 显示 "1.5.0",表示Gitbook也已经安装。

 $ gitbook build ./repository --output=./outputFolder
 显示“Starting build ...
      ENOENT, open 'repository/README.md'”
 但不会处理。

 $ gitbook build 
 显示“Starting build ...
     Cannot read property 'text' of undefined”

 $ gitbook init

显示如下错误

“TypeError: Cannot read property 'text' of undefined
at parseChapter (/usr/local/lib/node_modules/gitbook/lib/parse/summary.js:95:46)
at Array.map (native)
at Object.parseSummary [as summary] (/usr/local/lib/node_modules/gitbook/lib/parse/summary.js:134:6)
at /usr/local/lib/node_modules/gitbook/lib/generate/init.js:33:22
at _fulfilled (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:787:54)
at self.promiseDispatch.done (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:816:30)
at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:749:13)
at /usr/local/lib/node_modules/gitbook/node_modules/q/q.js:557:44
at flush (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:355:11)”
```

> 我在谷歌搜索“TypeError: Cannot read property 'text' of undefined”，找到一个 issue 提了这个问题，给出的解决方法是在 Summary 中去掉了空行。但对我的情况并不奏效。

## 我不是纠结于技术问题，而是我的作业还没完成，图书依然没有发布。http://cici19891.gitbooks.io/pythoncamp0/

**Comment by ZoomQuiet** [comment]
在 2015年3月23日 下午11:24，cici notifications@github.com写道：

> 出现“TypeError: Cannot read property 'text' of undefined”

嗯嗯嗯, 亲,你这么努力,连 node.js 都安装了,俺都忍不住来回答了,,,,

俺的测试:

$ git clone git@github.com:cici1989/pythoncamp0.git cici1989_pythoncamp0
$ cd cici1989_pythoncamp0
$ gitbook build ./
Starting build ...
Successfully built!

说明你的图书组织的成功的吻合 gitbook 规约,可以从本地编译成功;

然后:

$ git clone https://git.gitbook.com/cici19891/pythoncamp0.git
Cloning into 'pythoncamp0'...
fatal: unable to access
'https://git.gitbook.com/cici19891/pythoncamp0.git/': The requested
URL returned error: 403

嗯嗯嗯,看来无法替你测试 gitbook.io 上的仓库内容,

但是,无论 `Cannot read property` 还是之前有关仓库的配置中出现的大量 https 声明,
都体现出,你现在对 git 仓库的猜想方向有问题;
- 建议参考: [dpush |
  OMOOC.py](http://openmindclub.gitbooks.io/omooc-py/content/support/dpush.html)
- 对比自个儿的配置,理解 gitbook 出问题的原因
- 不能将错误的操作反复进行,期待某次能成功哪

整体上,背景条件要明确:
- github/gitbook 都是 git 仓库
- 但是, github/gitbook 仓库的访问姿势不统一
- 而且, 两个仓库现在不会自动同步
- gitbook 图书的编译问题,在后台 `book history` 中有非常明确的提示

> 将大妈的回复邮件又尝试之后依然不能发布图书，同时我收到了gitbook的build book失败的邮件，如下：
> 
> 确定不是双推的问题，在邮件给出的链接中找到关键词 install、plugins ，所以进行尝试了安装nodej使用命令来解决 GitBook 的 build 问题。
> 
> 但是出现了如题所示 Error，请问是什么错误？是我的摸索的具体过程：
> 
> 下载并安装 Nodejs
> 
>  $ note -v
>  显示"v0.12.0"表示已安装。
> 
> GitBook命令
> 
>  $ gitbook -V
>  显示 "1.5.0",表示Gitbook也已经安装。
> 
>  $ gitbook build ./repository --output=./outputFolder
>  显示“Starting build ...
>       ENOENT, open 'repository/README.md'”
>  但不会处理。
> 
>  $ gitbook build
>  显示“Starting build ...
>      Cannot read property 'text' of undefined”
> 
>  $ gitbook init
> 
> 显示如下错误
> 
> “TypeError: Cannot read property 'text' of undefined
> at parseChapter (/usr/local/lib/node_modules/gitbook/lib/parse/summary.js:95:46)
> at Array.map (native)
> at Object.parseSummary [as summary](/usr/local/lib/node_modules/gitbook/lib/parse/summary.js:134:6)
> at /usr/local/lib/node_modules/gitbook/lib/generate/init.js:33:22
> at _fulfilled (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:787:54)
> at self.promiseDispatch.done (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:816:30)
> at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:749:13)
> at /usr/local/lib/node_modules/gitbook/node_modules/q/q.js:557:44
> at flush (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:108:17)
> at process._tickCallback (node.js:355:11)”
> 
> 我在谷歌搜索“TypeError: Cannot read property 'text' of undefined”，找到一个 issue 提了这个问题，给出的解决方法是在 Summary 中去掉了空行。但对我的情况并不奏效。
> 
> 我不是纠结于技术问题，而是我的作业还没完成，图书依然没有发布。http://cici19891.gitbooks.io/pythoncamp0/
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by umulily** [comment]
![Uploading Y((I`L2HD({}A(]3_HSQ{BC.png . . .]()
